name: Automated tests  # запускает тесты на гитхаб


on:
  workflow_dispatch:
    inputs:
      deploymend_target:
        description: Choose target
        required: true
        default: second_test
        type: choice
        options:
          - first_test
          - second_test



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: first_test
        if: "github.event.inputs.deployment_target == 'fist_test'"
        run: pytest tests/test_button_page.py::test_button_exist --alluredir=allure-results
      - name: second_test
        if: "github.event.inputs.deployment_target == 'second_test'"
        run: pytest tests/test_like_a_buttonn_page.py::test_button2_exist --alluredir=allure-results
